### ISSUE TITLE
Merge `benders` repo into this repo

### ISSUE THREAD

**Issue by nglaeser** [benders5e/benders5e#8]
Done. Merged [`merge-prep` branch of `benders`](https://github.com/nglaeser/benders/tree/merge-prep) into new branch `class-drafts`.

#### Todos:
- Reconcile Homebrewery and website `.md` file versions
  - [x] General: PHB Intro, Equipment, Feats, Backgrounds, Appendix
  - Classes: 
    - [x] Airbender
    - [x] Barbarian (this repo only)
    - [x] Earthbender
    - [x] Fighter
    - [x] Firebender
    - [x] Monk
    - [x] Rogue
    - [x] Waterbender
- [x] Fix `\page` appearing on website (needed in HB)
